name: release

on:
  push:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with: {node-version: 18}
    - name: publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
